# 全局参数
robot_description: robot_description.launch.py

# 定位参数
localization:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 20.0
    publish_frequency: 20.0
    # 使用 T265 的位姿数据
    odom_topic: /camera/odom/sample

# 规划器参数
planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      use_astar: false

# 控制器参数
controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_dwb_controller/DwbController"
      # DWB 参数配置
      min_vel_x: 0.0
      max_vel_x: 0.5
      min_vel_y: 0.0
      max_vel_y: 0.0
      min_speed_xy: 0.0
      max_speed_xy: 0.5
      min_vel_theta: -1.0
      max_vel_theta: 1.0
      min_speed_theta: 0.0
      max_speed_theta: 1.0
      # 其他 DWB 参数...

# 恢复行为参数
recovery_server:
  ros__parameters:
    costmap_topic: global_costmap/costmap_raw
    footprint_topic: global_costmap/published_footprint
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"

# 避障参数
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /camera/odom/sample
    default_bt_xml_filename: $(find nav2_bt_navigator)/behavior_trees/navigate_w_replanning_and_recovery.xml